# Generated by Django 5.0.5 on 2024-05-09 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yoga', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YogaPathAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yogapath', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.yogapath')),
                ('yogasana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yoga.yogasana')),
            ],
            options={
                'unique_together': {('yogapath', 'yogasana')},
            },
        ),
        migrations.AddField(
            model_name='yogasana',
            name='paths',
            field=models.ManyToManyField(through='yoga.YogaPathAssociation', to='yoga.yogapath'),
        ),
    ]
